package RegexMatches;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Created by jiusa on 2017/3/31.
 */
public class RegexMatches {

  public static void main(String args[]) {

    // 按指定模式在字符串查找
    String html =
        "<html lang=\"zh-CN\"><head><meta charset=\"UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\"><meta name=\"renderer\" content=\"webkit\"><meta property=\"qc:admins\" content=\"15317273575564615446375\"><meta property=\"og:image\" content=\"https://static.segmentfault.com/v-58db88a6/global/img/touch-icon.png\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"><meta name=\"alexaVerifyID\" content=\"LkzCRJ7rPEUwt6fVey2vhxiw1vQ\"><meta name=\"apple-itunes-app\" content=\"app-id=958101793, app-argument=\"><title>angularjs学习笔记—指令a，ngHref - 学习笔记 - SegmentFault</title><meta name=\"description\" content=\"a {代码...} 当href属性为空时，点击的时候页面不会刷新了，我们再也不需要这样写了 {代码...} 一般和ng-click指令结合使用 {代码...} ngHref 一般和a标签结合使用。试想下我们的链接是这样的时候 {代码...} angu...\"><meta name=\"keywords\" content=\"javascript,angular.js\"><link rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"/opensearch.xml\" title=\"SegmentFault\"><link rel=\"shortcut icon\" href=\"https://static.segmentfault.com/v-58db88a6/global/img/favicon.ico\"><link rel=\"apple-touch-icon\" href=\"https://static.segmentfault.com/v-58db88a6/global/img/touch-icon.png\"><meta name=\"msapplication-TileColor\" content=\"#009a61\"><meta name=\"msapplication-square150x150logo\" content=\"https://static.segmentfault.com/v-58db88a6/global/img/touch-icon.png\"><link rel=\"alternate\" type=\"application/atom+xml\" title=\"SegmentFault 最新问题\" href=\"/feeds/questions\"><link rel=\"alternate\" type=\"application/atom+xml\" title=\"SegmentFault 最新文章\" href=\"/feeds/blogs\"><link rel=\"stylesheet\" href=\"https://static.segmentfault.com/v-58db88a6/global/css/global.css\"><link rel=\"stylesheet\" href=\"https://static.segmentfault.com/v-58db88a6/blog/css/blog.css\"><link rel=\"stylesheet\" href=\"https://static.segmentfault.com/v-58db88a6/global/css/responsive.css\"></head><body data-mod=\"blog\" class=\"blog-post \"><!--[if lt IE 9]><div class=\"alert alert-danger topframe\" role=\"alert\">你的浏览器实在<strong>太太太太太太旧了</strong>，放学别走，升级完浏览器再说 <a target=\"_blank\" class=\"alert-link\" href=\"http://browsehappy.com\">立即升级</a></div><![endif]--><img id=\"icon4weChat\" style=\"height: 0;width: 0;\" data-src=\"https://static.segmentfault.com/v-58db88a6/global/img/touch-icon-512.png\"><div class=\"global-nav sf-header sf-header--index\"><nav class=\"container nav\"><div class=\"hidden-sm hidden-lg hidden-md\"><div class=\"sf-header__logo sf-header__logo--response\"><h1><a></a></h1></div><div class=\"dropdown m-menu\"><a href=\"javascript:void(0);\" id=\"dLabel\" class=\"visible-xs-block m-toptools\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"><span class=\"glyphicon glyphicon-align-justify\"></span><span class=\"mobile-menu__unreadpoint\"></span></a><ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"dLabel\"><li class=\"mobile-menu__item\"><a href=\"/\">首页</a></li><li class=\"mobile-menu__item\"><a href=\"/news\" class=\"menu__item--new-show\">头条</a></li><li class=\"mobile-menu__item\"><a href=\"/questions\">问答</a></li><li class=\"mobile-menu__item\"><a href=\"/blogs\">专栏</a></li><li class=\"mobile-menu__item\"><a href=\"/lives\" class=\"menu__item--new-show\">讲堂</a></li><li class=\"mobile-menu__item\"><a href=\"/jobs\">职位</a></li><li class=\"mobile-menu__item\"><a href=\"/events\">活动</a></li><li class=\"mobile-menu__item\"><a href=\"/notes\">笔记</a></li><li class=\"mobile-menu__item\"><a href=\"/tags\">标签</a></li><li class=\"mobile-menu__item\"><a href=\"/users\">榜单</a></li></ul></div><a href=\"/user/login\" class=\"visible-xs-block pull-right m-ask m-toptools\"><span class=\"glyphicon glyphicon-log-in\"></span></a></div><div class=\"row hidden-xs\"><div class=\"col-sm-10 col-md-8 col-lg-7\"><div class=\"sf-header__logo\"><h1><a href=\"/\">SegmentFault</a></h1></div><ul class=\"menu list-inline pull-left hidden-xs\"><li class=\"menu__item\"><a href=\"/news\" class=\"menu__item--new-show\">头条</a></li><li class=\"menu__item\"><a href=\"/questions\">问答</a></li><li class=\"menu__item\"><a href=\"/blogs\">专栏</a></li><li class=\"menu__item\"><a href=\"/lives\" class=\"menu__item--new-show\">讲堂</a></li><li class=\"menu__item\"><a href=\"/jobs\">职位</a></li><li class=\"menu__item\"><a href=\"/events\">活动</a></li></ul></div><div class=\"col-sm-2 col-md-4 col-lg-5 text-right\"><form action=\"/search\" class=\"header-search  hidden-sm hidden-xs mr20\"><button class=\"btn btn-link\"><span class=\"sr-only\">搜索</span><span class=\"glyphicon glyphicon-search\"></span></button><input id=\"searchBox\" name=\"q\" type=\"text\" placeholder=\"输入关键字搜索\" class=\"form-control\" value=\"\"></form><ul class=\"opts list-inline hidden-xs\"><li class=\"opts__item message has-unread\"><a target=\"_blank\" href=\"/tour\"><span class=\"sr-only\">消息</span><span id=\"messageCount\" class=\"fa fa-hand-peace-o\"></span></a></li><li class=\"opts__item\"><a href=\"/user/login\" class=\"SFLogin em ml10\" onclick=\"_gaq.push(['_trackEvent', 'Button', 'Click', 'Login']);\">注册 ·\n"
            + "                                        登录</a></li></ul></div></div></nav></div><div class=\"global-navTags\"><div class=\"container\"><nav class=\" nav\"><ul class=\"nav__list\"><li class=\"nav__item\"><a href=\"/\"><i class=\"fa fa-home\"></i>home\n"
            + "                            </a></li><li class=\"nav__item nav__item--split\"><a><span class=\"split\"></span></a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/javascript\">javascript</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/php\">php</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/python\">python</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/java\">java</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/mysql\">mysql</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/ios\">ios</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/android\">android</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/node.js\">node.js</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/html5\">html5</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/linux\">linux</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/c%2B%2B\">c++</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/css3\">css3</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/git\">git</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/golang\">golang</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/ruby\">ruby</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/vim\">vim</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/docker\">docker</a></li><li class=\"nav__item tag-nav__item\"><a href=\"/t/mongodb\">mongodb</a></li><li class=\"nav__item nav__item--more\" data-open=\"0\"><a class=\"nav__item--more-link\" href=\"/tags\"><div class=\"tag__more\"><i class=\"tag__more--icon\"></i><i class=\"tag__more--icon\"></i><i class=\"tag__more--icon\"></i></div></a></li></ul><div class=\"tag-mgr__box hide\"><input class=\"tag-mgr__query\" type=\"text\" placeholder=\"搜索关注的标签\" data-tags=\"null\"><div class=\"mCustomScrollbar _mCS_1 mCS-autoHide mCS_no_scrollbar\" data-mcs-theme=\"minimal-dark\" style=\"position: relative; overflow: visible;\"><div id=\"mCSB_1\" class=\"mCustomScrollBox mCS-minimal-dark mCSB_vertical mCSB_outside\" style=\"max-height: 0px;\" tabindex=\"0\"><div id=\"mCSB_1_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\"><ul class=\"tag-mgr__list\"></ul></div></div><div id=\"mCSB_1_scrollbar_vertical\" class=\"mCSB_scrollTools mCSB_1_scrollbar mCS-minimal-dark mCSB_scrollTools_vertical\" style=\"display: none;\"><div class=\"mCSB_draggerContainer\"><div id=\"mCSB_1_dragger_vertical\" class=\"mCSB_dragger\" style=\"position: absolute; min-height: 50px; top: 0px;\" oncontextmenu=\"return false;\"><div class=\"mCSB_dragger_bar\" style=\"line-height: 50px;\"></div></div><div class=\"mCSB_draggerRail\"></div></div></div></div><a href=\"/tags\" class=\"btn btn-primary btn-sm tag-mgr__btn\">标签管理</a></div></nav></div></div>\n"
            + "    <div class=\"wrap\">\n"
            + "    <div class=\"post-topheader custom-\">\n"
            + "        <div class=\"container\">\n"
            + "            <div class=\"row\">\n"
            + "                <div class=\"col-md-9 col-sm-8 col-xs-12\">\n"
            + "                    <span class=\"post-topheader__title--icon-symbol\">文</span>\n"
            + "\n"
            + "                    <div class=\"post-topheader__info\" data-username=\"小俞\" data-userslug=\"yuyang040160120\" data-useravatar=\"https://sfault-avatar.b0.upaiyun.com/355/791/3557912364-55484a6189d29_big64\">\n"
            + "\n"
            + "                        <h1 class=\"h3 post-topheader__info--title\" id=\"articleTitle\" data-id=\"1190000002628630\">\n"
            + "\n"
            + "                            <a href=\"/a/1190000002628630\"> angularjs学习笔记—指令a，ngHref</a>\n"
            + "                        </h1>\n"
            + "\n"
            + "                        <ul class=\"taglist--inline inline-block article__title--tag mr10\">\n"
            + "                                                            <li class=\"tagPopup mb5\"><a class=\"tag\" href=\"/t/javascript/blogs\" data-toggle=\"popover\" data-img=\"https://sfault-avatar.b0.upaiyun.com/195/823/1958237468-1040000000089436_huge256\" data-placement=\"top\" data-original-title=\"javascript\" data-id=\"1040000000089436\">javascript</a></li>\n"
            + "                                                            <li class=\"tagPopup mb5\"><a class=\"tag\" href=\"/t/angular.js/blogs\" data-toggle=\"popover\" data-img=\"https://sfault-avatar.b0.upaiyun.com/327/297/3272974306-1040000000210853_huge256\" data-placement=\"top\" data-original-title=\"angular.js\" data-id=\"1040000000210853\">angular.js</a></li>\n"
            + "                                                    </ul>\n"
            + "\n"
            + "                        <div class=\"article__author\">\n"
            + "                            <a href=\"/u/yuyang040160120\" class=\"mr5 \"><strong>小俞</strong></a>\n"
            + "                            2015年03月28日发布\n"
            + "                                                                                </div>\n"
            + "                    </div>\n"
            + "                </div>\n"
            + "                <div class=\"col-md-3 col-sm-4 hidden-xs\">\n"
            + "                    <ul class=\"post-topheader__side list-unstyled\">\n"
            + "                        <li>\n"
            + "                                                                                                <button type=\"button\" class=\"btn btn-success btn-sm\" data-id=\"1190000002628630\" id=\"sideLike\">推荐\n"
            + "                                    </button>\n"
            + "                                                                                        <strong id=\"sideLiked\">1</strong> 推荐\n"
            + "                        </li>\n"
            + "                        <li>\n"
            + "                                                                                                <button type=\"button\" id=\"sideBookmark\" class=\"btn btn-default btn-sm\" data-id=\"1190000002628630\" data-type=\"article\">收藏\n"
            + "                                    </button>\n"
            + "                                                                                        <strong id=\"sideBookmarked\">8</strong> 收藏，<strong class=\"no-stress\">18.6k</strong> 浏览\n"
            + "                        </li>\n"
            + "                    </ul>\n"
            + "                </div>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "    </div><!-- end .post-topheader -->\n"
            + "\n"
            + "    <div class=\"container mt30\">\n"
            + "        <div class=\"row\">\n"
            + "            <div class=\"col-xs-12 col-md-9 main \">\n"
            + "\n"
            + "                \n"
            + "                <div class=\"article fmt article__content\" data-id=\"1190000002628630\" data-license=\"cc\">\n"
            + "                    \n"
            + "<h2 id=\"articleHeader0\">a</h2>\n"
            + "\n"
            + "<div class=\"widget-codetool\" style=\"display: none;\">\n"
            + "      <div class=\"widget-codetool--inner\">\n"
            + "      <span class=\"selectCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"全选\"></span>\n"
            + "      <span type=\"button\" class=\"copyCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" data-clipboard-text=\"<a href=&quot;&quot;>点击我啊</a>\n"
            + "\" title=\"\" data-original-title=\"复制\"></span>\n"
            + "      <span type=\"button\" class=\"saveToNote code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"放进笔记\"></span>\n"
            + "      </div>\n"
            + "      </div><pre class=\"hljs xml\"><code><span class=\"hljs-tag\">&lt;<span class=\"hljs-title\">a</span> <span class=\"hljs-attribute\">href</span>=<span class=\"hljs-value\">\"\"</span>&gt;</span>点击我啊<span class=\"hljs-tag\">&lt;/<span class=\"hljs-title\">a</span>&gt;</span>\n"
            + "</code></pre>\n"
            + "\n"
            + "<p>当href属性为空时，点击的时候页面不会刷新了，我们再也不需要这样写了</p>\n"
            + "\n"
            + "<div class=\"widget-codetool\" style=\"display:none;\">\n"
            + "      <div class=\"widget-codetool--inner\">\n"
            + "      <span class=\"selectCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"全选\"></span>\n"
            + "      <span type=\"button\" class=\"copyCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" data-clipboard-text=\"<a href=&quot;javascript:void(0)&quot;>点击我啊</a>\n"
            + "\" title=\"\" data-original-title=\"复制\"></span>\n"
            + "      <span type=\"button\" class=\"saveToNote code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"放进笔记\"></span>\n"
            + "      </div>\n"
            + "      </div><pre class=\"hljs xml\"><code><span class=\"hljs-tag\">&lt;<span class=\"hljs-title\">a</span> <span class=\"hljs-attribute\">href</span>=<span class=\"hljs-value\">\"javascript:void(0)\"</span>&gt;</span>点击我啊<span class=\"hljs-tag\">&lt;/<span class=\"hljs-title\">a</span>&gt;</span>\n"
            + "</code></pre>\n"
            + "\n"
            + "<p>一般和<em>ng-click</em>指令结合使用</p>\n"
            + "\n"
            + "<div class=\"widget-codetool\" style=\"display:none;\">\n"
            + "      <div class=\"widget-codetool--inner\">\n"
            + "      <span class=\"selectCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"全选\"></span>\n"
            + "      <span type=\"button\" class=\"copyCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" data-clipboard-text=\"#html\n"
            + "<div ng-controller=&quot;LearnCtrl&quot;>\n"
            + "    <a href=&quot;&quot; ng-click=&quot;click()&quot;>点击我啊</a>\n"
            + "</div>\n"
            + "\n"
            + "#script\n"
            + "angular.module('learnModule', [])    \n"
            + "        .controller('LearnCtrl', function ($scope) {\n"
            + "            $scope.click = function () {\n"
            + "                alert('你点击我了');\n"
            + "            }\n"
            + "        });\n"
            + "\" title=\"\" data-original-title=\"复制\"></span>\n"
            + "      <span type=\"button\" class=\"saveToNote code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"放进笔记\"></span>\n"
            + "      </div>\n"
            + "      </div><pre class=\"hljs php\"><code><span class=\"hljs-comment\">#html</span>\n"
            + "&lt;div ng-controller=<span class=\"hljs-string\">\"LearnCtrl\"</span>&gt;\n"
            + "    &lt;a href=<span class=\"hljs-string\">\"\"</span> ng-click=<span class=\"hljs-string\">\"click()\"</span>&gt;点击我啊&lt;/a&gt;\n"
            + "&lt;/div&gt;\n"
            + "\n"
            + "<span class=\"hljs-comment\">#script</span>\n"
            + "angular.module(<span class=\"hljs-string\">'learnModule'</span>, [])    \n"
            + "        .controller(<span class=\"hljs-string\">'LearnCtrl'</span>, <span class=\"hljs-function\"><span class=\"hljs-keyword\">function</span> <span class=\"hljs-params\">(<span class=\"hljs-variable\">$scope</span>)</span> </span>{\n"
            + "            <span class=\"hljs-variable\">$scope</span>.click = <span class=\"hljs-function\"><span class=\"hljs-keyword\">function</span> <span class=\"hljs-params\">()</span> </span>{\n"
            + "                alert(<span class=\"hljs-string\">'你点击我了'</span>);\n"
            + "            }\n"
            + "        });\n"
            + "</code></pre>\n"
            + "\n"
            + "<h2 id=\"articleHeader1\">ngHref</h2>\n"
            + "\n"
            + "<p>一般和a标签结合使用。试想下我们的链接是这样的时候</p>\n"
            + "\n"
            + "<div class=\"widget-codetool\" style=\"display:none;\">\n"
            + "      <div class=\"widget-codetool--inner\">\n"
            + "      <span class=\"selectCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"全选\"></span>\n"
            + "      <span type=\"button\" class=\"copyCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" data-clipboard-text=\"<a href=&quot;/avatar/{{hash}}&quot;>link1</a>\n"
            + "\" title=\"\" data-original-title=\"复制\"></span>\n"
            + "      <span type=\"button\" class=\"saveToNote code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"放进笔记\"></span>\n"
            + "      </div>\n"
            + "      </div><pre class=\"hljs xml\"><code><span class=\"hljs-tag\">&lt;<span class=\"hljs-title\">a</span> <span class=\"hljs-attribute\">href</span>=<span class=\"hljs-value\">\"/avatar/{{hash}}\"</span>&gt;</span>link1<span class=\"hljs-tag\">&lt;/<span class=\"hljs-title\">a</span>&gt;</span>\n"
            + "</code></pre>\n"
            + "\n"
            + "<p>angularjs的执行都是在DOM渲染完成之后，如果我们在angularjs执行这个表达式之前点击了链接，那么就直接访问了<em>/avatar/{{hash}}</em>，一般都会跳转到404页面，用户体验太烂了。</p>\n"
            + "\n"
            + "<p>使用了ngHref就就可以避免出现这种问题。</p>\n"
            + "\n"
            + "<div class=\"widget-codetool\" style=\"display:none;\">\n"
            + "      <div class=\"widget-codetool--inner\">\n"
            + "      <span class=\"selectCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"全选\"></span>\n"
            + "      <span type=\"button\" class=\"copyCode code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" data-clipboard-text=\"<a ng-href=&quot;/avatar/{{hash}}&quot;>link1</a>\n"
            + "\" title=\"\" data-original-title=\"复制\"></span>\n"
            + "      <span type=\"button\" class=\"saveToNote code-tool\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"放进笔记\"></span>\n"
            + "      </div>\n"
            + "      </div><pre class=\"hljs xml\"><code><span class=\"hljs-tag\">&lt;<span class=\"hljs-title\">a</span> <span class=\"hljs-attribute\">ng-href</span>=<span class=\"hljs-value\">\"/avatar/{{hash}}\"</span>&gt;</span>link1<span class=\"hljs-tag\">&lt;/<span class=\"hljs-title\">a</span>&gt;</span>\n"
            + "</code></pre>\n"
            + "\n"
            + "<blockquote>\n"
            + "  <p>如果链接中有表达式，就使用ngHref代替href</p>\n"
            + "</blockquote>\n"
            + "\n"
            + "                </div>\n"
            + "                                                \n"
            + "                <div class=\"clearfix mt10\">\n"
            + "\n"
            + "                    <ul class=\"article-operation list-inline pull-left\">\n"
            + "                        <li><a href=\"/a/1190000002628630\" class=\"text-muted\">2015年03月28日发布</a></li>\n"
            + "                                                                                                                            <li class=\"dropdown js__content-ops\" data-module=\"article\" data-id=\"1190000002628630\" data-typetext=\"文章\">\n"
            + "                                <a href=\"javascript:void(0);\" class=\"dropdown-toggle text-muted\" data-toggle=\"dropdown\">更多<b class=\"caret\"></b></a>\n"
            + "                                <ul class=\"dropdown-menu dropdown-menu-left\">\n"
            + "                                    <li><a href=\"#911\" data-toggle=\"modal\" data-target=\"#911\" data-action=\"report\">举报</a></li>\n"
            + "                                                                            \n"
            + "                                                                                                                        \n"
            + "                                        \n"
            + "                                                                    </ul>\n"
            + "                            </li>\n"
            + "                                            </ul>\n"
            + "                </div>\n"
            + "                <div class=\"mt10 text-center\"><button type=\"button\" id=\"mainLike\" data-id=\"1190000002628630\" class=\"btn btn-success btn-lg mr15 \">\n"
            + "                                1 推荐\n"
            + "                            </button><button type=\"button\" id=\"mainBookmark\" data-type=\"article\" data-id=\"1190000002628630\" class=\"btn btn-default btn-lg mr15 \">\n"
            + "                                收藏\n"
            + "                            </button></div>\n"
            + "                                    <div class=\"recommend-post pt30 mt40 mb30 border-top\">\n"
            + "                        <div class=\"row\">\n"
            + "                            <div class=\"col-md-8\">\n"
            + "                                                                    <h4 class=\"mt0\">你可能感兴趣的文章</h4>\n"
            + "                                    <ul class=\"widget-links list-unstyled\">\n"
            + "                                                                                    <li class=\"widget-links__item\">\n"
            + "                                                <a href=\"/a/1190000004907484\" title=\"Angularjs学习笔记指令\">Angularjs学习笔记指令</a>\n"
            + "                                                <small class=\"text-muted\">\n"
            + "                                                    14 收藏，635\n"
            + "                                                    浏览\n"
            + "                                                </small>\n"
            + "                                            </li>\n"
            + "                                                                                    <li class=\"widget-links__item\">\n"
            + "                                                <a href=\"/a/1190000003004348\" title=\"AngularJs学习笔记-第一章-指令(2)\">AngularJs学习笔记-第一章-指令(2)</a>\n"
            + "                                                <small class=\"text-muted\">\n"
            + "                                                    5 收藏，779\n"
            + "                                                    浏览\n"
            + "                                                </small>\n"
            + "                                            </li>\n"
            + "                                                                                    <li class=\"widget-links__item\">\n"
            + "                                                <a href=\"/a/1190000003013749\" title=\"AngularJs学习笔记-第六章-动画(ngAnimate)\">AngularJs学习笔记-第六章-动画(ngAnimate)</a>\n"
            + "                                                <small class=\"text-muted\">\n"
            + "                                                    15 收藏，6.2k\n"
            + "                                                    浏览\n"
            + "                                                </small>\n"
            + "                                            </li>\n"
            + "                                                                            </ul>\n"
            + "                                                            </div>\n"
            + "                            <div class=\"col-md-4\">\n"
            + "                                                            </div>\n"
            + "                        </div>\n"
            + "\n"
            + "                    </div>\n"
            + "                                <!-- <ul class=\"list-unstyled text-muted mt30\">\n"
            + "                                        <li>上一篇：<a href=\"/a/1190000002625738\">angularjs学习笔记—工具方法</a></li>\n"
            + "                                                            <li class=\"mt5\">下一篇：<a href=\"/a/1190000002632671\">angularjs学习笔记—指令input</a></li>\n"
            + "                                    </ul> -->\n"
            + "\n"
            + "                <h2 class=\"h4 post-comment-title\"></h2>\n"
            + "                \n"
            + "        <div class=\"comments--news comments--default\" data-id=\"1190000002628630\" data-user-id=\"\" data-author-id=\"1030000002547055 \" data-is-admin=\"null\">\n"
            + "        <div class=\"mb10\">\n"
            + "            <strong class=\"comments-stat pull-left mr10\">评论</strong>\n"
            + "            <div class=\"btn-group comments-sort\">\n"
            + "                <button type=\"button\" class=\"btn btn-link btn-sm dropdown-toggle\" data-toggle=\"dropdown\">\n"
            + "                    <span class=\"comments-sort-text\">默认排序</span> <span class=\"caret\"></span>\n"
            + "                </button>\n"
            + "                <ul class=\"dropdown-menu\" role=\"menu\">\n"
            + "                    <li><a href=\"javascript:;\" data-sort=\"default\">默认排序</a></li>\n"
            + "                    <li><a href=\"javascript:;\" data-sort=\"asc\">时间排序</a></li>\n"
            + "                </ul>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "        <div class=\"comments-container\">\n"
            + "                                <div class=\"comments-list\">\n"
            + "            </div>\n"
            + "    <div class=\"comments-loading hide\">载入中...</div>\n"
            + "    <div class=\"comments-more hide\"><a href=\"javascript:;\">显示更多评论</a></div>\n"
            + "\n"
            + "                        <div class=\"comments-box\">\n"
            + "                <div class=\"pull-left\">\n"
            + "                    <img class=\"avatar-32 \" src=\"https://static.segmentfault.com/v-58db88a6/global/img/user-128.png\" alt=\"\">\n"
            + "                </div>\n"
            + "                <div class=\"comments-box-content\">\n"
            + "                    <form action=\"/api/article/[id]/comments/add\">\n"
            + "                        <div class=\"form-group mb0\">\n"
            + "                                            <textarea name=\"text\" rows=\"3\" class=\"form-control\" placeholder=\"文明社会，理性评论\"></textarea>\n"
            + "\n"
            + "                            <div class=\"mt15 text-right\">\n"
            + "                                <button type=\"button\" class=\"hide\"></button>\n"
            + "                                <button class=\" btn btn-primary\" type=\"button\">发布评论</button>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </form>\n"
            + "\n"
            + "                </div>\n"
            + "            </div>\n"
            + "                    </div>\n"
            + "    </div>\n"
            + "\n"
            + "\n"
            + "\n"
            + "\n"
            + "\n"
            + "\n"
            + "                                    \n"
            + "                \n"
            + "            </div><!-- /.main -->\n"
            + "\n"
            + "\n"
            + "            <div class=\"col-xs-12 col-md-3 side\">\n"
            + "                <div class=\"sfad-sidebar\">\n"
            + "      <div class=\"sfad-item\">\n"
            + "    <ins data-revive-zoneid=\"2\" data-revive-block=\"1\" data-revive-target=\"_blank\" data-revive-ct0=\"1490788468\" data-revive-id=\"0042ddc520dc895b7aa784fe6f9339bd\"></ins>\n"
            + "    <button class=\"close\" type=\"button\" aria-hidden=\"true\">×</button>\n"
            + "</div>\n"
            + "\n"
            + "  </div>\n"
            + "\n"
            + "\n"
            + "                <div class=\"widget-box widget-box--blog-info\">\n"
            + "                    <div class=\"blog__sidebar-author \">\n"
            + "                                                    <button type=\"button\" class=\"btn btn-sm btn-success follow-user ml10 pull-right\" data-do=\"follow\" data-type=\"user\" data-id=\"1030000002547055\">关注作者\n"
            + "                            </button>\n"
            + "                        \n"
            + "                        <div class=\"article__widget--author\">\n"
            + "                            <a href=\"/u/yuyang040160120\">\n"
            + "                                <img class=\"avatar-40\" src=\"https://sfault-avatar.b0.upaiyun.com/355/791/3557912364-55484a6189d29_big64\" alt=\"小俞\">\n"
            + "                            </a>\n"
            + "                            <a class=\"article__widget-author-name\" href=\"/u/yuyang040160120\">\n"
            + "                                <strong>小俞</strong>\n"
            + "                            </a>\n"
            + "                            <p class=\"article__widget-author-text-muted mb0\">\n"
            + "                                <span>7.7k 声望</span>\n"
            + "\n"
            + "                            </p>\n"
            + "\n"
            + "\n"
            + "                        </div>\n"
            + "\n"
            + "\n"
            + "                    </div>\n"
            + "                                        <div class=\"blog__sidebar-blog-name\">\n"
            + "                        <p class=\"article__widget-author-text-muted mt15 mb5\">发布于专栏</p>\n"
            + "\n"
            + "                        <h4 class=\"fz16\"><a href=\"/blog/yuyang040160120\">学习笔记</a></h4>\n"
            + "                        <p class=\"article__widget-author-desc\">自我学习总结</p>\n"
            + "\n"
            + "                        <p>\n"
            + "                            <span class=\"article__widget-author-text-muted\">113 人关注</span>\n"
            + "                            \n"
            + "                                                                    <button type=\"button mb20\" class=\"btn btn-sm btn-default follow-article pull-right\" data-do=\"follow\" data-type=\"blog\" data-id=\"1200000002547672\">关注专栏\n"
            + "                                    </button>\n"
            + "                                \n"
            + "                                                    </p>\n"
            + "\n"
            + "                    </div>\n"
            + "                    \n"
            + "\n"
            + "                </div>\n"
            + "\n"
            + "\n"
            + "                \n"
            + "                    <div data-type=\"widget\" data-api=\"/api/bookmarkArchive/hots\" data-api-overwrite=\"/api/bookmarkArchive/1190000002628630/related\">\n"
            + "        <script src=\"//hm.baidu.com/hm.js?e23800c454aa573c0ccb16b52665ac26\"></script><script async=\"\" src=\"//www.google-analytics.com/analytics.js\"></script><script type=\"text/template\">\n"
            + "            <div class=\"widget-box widget-box--bookmark no-border\">\n"
            + "                <h4 class=\"widget-box__title\">相关收藏夹 <a id=\"widgetBookmarkRefresh\" class=\"userstab pull-right\"\n"
            + "                                                          href=\"javascript:;\">换一组</a></h4>\n"
            + "                <ul class=\"widget-links list-unstyled media\">\n"
            + "                    <% _.each(data,function(d){ %>\n"
            + "                    <li class=\"widget-links__item\">\n"
            + "                        <img class=\"pull-left pattern pattern-<%= d.id%19 %> mr10\" src=\"https://static.segmentfault.com/v-58db88a6/global/img/pattern/<%= d.id%10 ? d.id%10 : 10 %>.svg\" width=\"32\">\n"
            + "                        <div class=\"media-body\">\n"
            + "                            <a target=\"_blank\" class=\"ellipsis mr0\" href=\"<%- d.url %>\"><%= d.name %></a>\n"
            + "                            <p class=\"mb0\">\n"
            + "                                <span><%- d.num %></span> 个条目 <span class=\"division\">|</span> <span><%- d.followers %></span> 人关注\n"
            + "                            </p>\n"
            + "                        </div>\n"
            + "                    </li>\n"
            + "                    <% }) %>\n"
            + "                </ul>\n"
            + "            </div>\n"
            + "        </script>\n"
            + "    \n"
            + "            <div class=\"widget-box widget-box--bookmark no-border\">\n"
            + "                <h4 class=\"widget-box__title\">相关收藏夹 <a id=\"widgetBookmarkRefresh\" class=\"userstab pull-right\" href=\"javascript:;\">换一组</a></h4>\n"
            + "                <ul class=\"widget-links list-unstyled media\">\n"
            + "                    \n"
            + "                    <li class=\"widget-links__item\">\n"
            + "                        <img class=\"pull-left pattern pattern-8 mr10\" src=\"https://static.segmentfault.com/v-58db88a6/global/img/pattern/10.svg\" width=\"32\">\n"
            + "                        <div class=\"media-body\">\n"
            + "                            <a target=\"_blank\" class=\"ellipsis mr0\" href=\"/bookmark/1230000008578790\">干货收集</a>\n"
            + "                            <p class=\"mb0\">\n"
            + "                                <span>4</span> 个条目 <span class=\"division\">|</span> <span>0</span> 人关注\n"
            + "                            </p>\n"
            + "                        </div>\n"
            + "                    </li>\n"
            + "                    \n"
            + "                    <li class=\"widget-links__item\">\n"
            + "                        <img class=\"pull-left pattern pattern-2 mr10\" src=\"https://static.segmentfault.com/v-58db88a6/global/img/pattern/8.svg\" width=\"32\">\n"
            + "                        <div class=\"media-body\">\n"
            + "                            <a target=\"_blank\" class=\"ellipsis mr0\" href=\"/bookmark/1230000008537098\">front-end </a>\n"
            + "                            <p class=\"mb0\">\n"
            + "                                <span>4</span> 个条目 <span class=\"division\">|</span> <span>0</span> 人关注\n"
            + "                            </p>\n"
            + "                        </div>\n"
            + "                    </li>\n"
            + "                    \n"
            + "                    <li class=\"widget-links__item\">\n"
            + "                        <img class=\"pull-left pattern pattern-16 mr10\" src=\"https://static.segmentfault.com/v-58db88a6/global/img/pattern/10.svg\" width=\"32\">\n"
            + "                        <div class=\"media-body\">\n"
            + "                            <a target=\"_blank\" class=\"ellipsis mr0\" href=\"/bookmark/1230000008327770\">mobile</a>\n"
            + "                            <p class=\"mb0\">\n"
            + "                                <span>7</span> 个条目 <span class=\"division\">|</span> <span>0</span> 人关注\n"
            + "                            </p>\n"
            + "                        </div>\n"
            + "                    </li>\n"
            + "                    \n"
            + "                </ul>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "\n"
            + "\n"
            + "                <div class=\"widget-share__full\" data-text=\"angularjs学习笔记—指令a，ngHref\" data-url=\"https://segmentfault.com/a/1190000002628630\" data-shorturl=\"http://sfau.lt/b5lbZq\"><div style=\"margin-bottom:10px;\">分享扩散：</div><div class=\"widget-share-network sharer-0\" style=\"display: block;\"><ul class=\"sn-inline\"><li data-network=\"weibo\"><a href=\"javascript:void(0);\" class=\"entypo-weibo icon-sn-weibo share-1\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"分享至新浪微博\">新浪微博</a></li><li data-network=\"wechart\"><a href=\"javascript:void(0);\" class=\"entypo-wechart icon-sn-weixin share-2\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"分享至微信\">微信</a></li><li data-network=\"twitter\"><a href=\"javascript:void(0);\" class=\"entypo-twitter icon-sn-twitter share-3\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"分享至 Twitter\">Twitter</a></li><li data-network=\"facebook\"><a href=\"javascript:void(0);\" class=\"entypo-facebook icon-sn-facebook share-4\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"\" data-original-title=\"分享至 Facebook\">Facebook</a></li></ul></div><a type=\"button\" class=\"btn btn-sm shareMore btn-sn-more\" data-toggle=\"popover\" data-placement=\"top\" data-url=\"https://segmentfault.com/a/1190000002628630\" data-shorturl=\"http://sfau.lt/b5lbZq\"><span class=\"icon-sn-dotted\" data-original-title=\"\" title=\"\"></span><strong class=\"visible-xs-inline\">•••</strong></a></div>\n"
            + "\n"
            + "                <div class=\"post-nav hidden-xs side-outline hidden-sm\" style=\"display: block; width: 100%; top: 0px;\">\n"
            + "                    <div class=\"panel panel-default widget-outline\">\n"
            + "                        <div class=\"panel-heading\">文章目录</div>\n"
            + "                        <div class=\"panel-body\">\n"
            + "                            <div class=\"nav-body\" style=\"top: 0px;\">\n"
            + "                                <div class=\"highlight-title\" style=\"top: 0px; height: 27px; display: none;\"></div>\n"
            + "                                <ul class=\"articleIndex\"><li class=\"\"><a href=\"#articleHeader0\">a</a></li><li class=\"\"><a href=\"#articleHeader1\">ngHref</a></li></ul>\n"
            + "                            </div>\n"
            + "                        </div>\n"
            + "                    </div>\n"
            + "                </div>\n"
            + "            </div><!-- /.side -->\n"
            + "        </div>\n"
            + "    </div>\n"
            + "</div>\n"
            + "\n"
            + "<div id=\"shareToWeiboModal\" class=\"modal\" tabindex=\"-1\">\n"
            + "    <div class=\"modal-dialog\">\n"
            + "        <div class=\"modal-content\">\n"
            + "            <div class=\"modal-header\">\n"
            + "                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">\n"
            + "                    <span aria-hidden=\"true\">×</span><span class=\"sr-only\">Close</span>\n"
            + "                </button>\n"
            + "                <h4 class=\"modal-title\">分享</h4>\n"
            + "            </div>\n"
            + "            <div class=\"modal-body\">\n"
            + "                <p class=\"sfModal-content\">\n"
            + "                    分享到微博？\n"
            + "                </p>\n"
            + "            </div>\n"
            + "            <div class=\"modal-footer\">\n"
            + "                <button type=\"button\" class=\"btn btn-default dont-likeweibo\" data-dismiss=\"modal\">取消</button>\n"
            + "                <a href=\"\" id=\"shareLink\" class=\"btn btn-primary done-btn\" target=\"_blank\" onclick=\"$('#shareToWeiboModal').modal('hide')\">分享</a>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "    </div>\n"
            + "</div>\n"
            + "\n"
            + "    \n"
            + "\n"
            + "<script type=\"text/template\" id=\"regNext\">\n"
            + "        <div class=\"row flex-vertical-center\">\n"
            + "        <div class=\"col-md-12\">\n"
            + "            <p class=\"mb0\" style=\"font-size: 14px; margin-right:50px; font-family: Source Code Pro,Consolas,Menlo,Monaco,Courier New,monospace;\">\n"
            + "                    &lt;space&gt; or &lt;tab&gt;，这里有和你习惯相同的程序员\n"
            + "            </p>\n"
            + "            <button class=\"btn btn-primary SFLogin mr10\"\n"
            + "                    onclick='ga(\"send\", \"event\", \"join button\", \"clicked\", \"footer welcome popup\");'>投入组织怀抱\n"
            + "            </button>\n"
            + "            <button class=\"btn  btn-default  tomorrow\">Python 怎么办</button>\n"
            + "        </div>\n"
            + "\n"
            + "    </div>\n"
            + "</script>\n"
            + "\n"
            + "<div class=\"widget-register widget-welcome-question mt20 hidden-xs hidden-sm widget-welcome widget-register-slideUp\">\n"
            + "    <div class=\"container\">\n"
            + "        <div class=\"row flex-vertical-center\">\n"
            + "            <div class=\"col-sm-12 col-md-8\">\n"
            + "                <p class=\"mb0\">\n"
            + "                                                                你好！看起来你挺喜欢这个内容，但是你还没有注册帐号。 <br><br>当你创建了帐号，我们能准确地追踪你关注的问题，在有新答案或内容的时候收到网页和邮件通知。<br>还能直接向作者咨询更多细节。如果上面的内容有帮助，记得点赞 (♥◠‿◠)ﾉ 表示感谢。\n"
            + "                                    </p>\n"
            + "\n"
            + "            </div>\n"
            + "            <div class=\"col-sm-12 col-lg-3 col-lg-offset-1 col-md-4\">\n"
            + "                <button class=\"btn btn-primary btn-lg SFLogin  mr10\" onclick=\"ga(&quot;send&quot;, &quot;event&quot;, &quot;join button&quot;, &quot;clicked&quot;, &quot;footer welcome popup&quot;);\">立即注册\n"
            + "                </button>\n"
            + "                <button class=\"btn btn-lg btn-default  tomorrow\">明天提醒我</button>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "    </div>\n"
            + "</div>\n"
            + "\n"
            + "<div class=\"modal widget-911\" id=\"911\" tabindex=\"-1\">\n"
            + "  <div class=\"modal-dialog\">\n"
            + "    <div class=\"modal-content\">\n"
            + "      <div class=\"modal-header\">\n"
            + "        <button class=\"close\" data-dismiss=\"modal\" type=\"button\">\n"
            + "          <span aria-hidden=\"true\">×</span>\n"
            + "          <span class=\"sr-only\">Close</span>\n"
            + "        </button>\n"
            + "        <h4 class=\"modal-title\"><span data-model=\"action\"></span><span data-model=\"type\"></span></h4>\n"
            + "      </div>\n"
            + "      <div class=\"modal-body\">\n"
            + "        <form id=\"reportForm\">\n"
            + "          <!-- 后台返回信息 -->\n"
            + "          <p class=\"alert alert-warning\" data-model=\"returnMsg\"></p>\n"
            + "          <div data-role=\"base\">\n"
            + "            <p>\n"
            + "              <strong class=\"required\">我要<span data-model=\"action\"></span>该<span data-model=\"type\"></span>，理由是：</strong>\n"
            + "            </p>\n"
            + "            <ul class=\"list-unstyled\" data-model=\"list\"></ul>\n"
            + "          </div>\n"
            + "        </form>\n"
            + "      </div>\n"
            + "      <div class=\"modal-footer\">\n"
            + "        <button class=\"btn btn-default pull-left\" type=\"button\" data-role=\"back\" style=\"display:none\">返回重选</button>\n"
            + "                <button class=\"btn btn-default\" data-dismiss=\"modal\" type=\"button\">取消</button>\n"
            + "        <button class=\"btn btn-primary\" data-role=\"submit\" type=\"button\">提交</button>\n"
            + "      </div>\n"
            + "    </div><!-- /.modal-content -->\n"
            + "  </div><!-- /.modal-dialog -->\n"
            + "</div><!-- /.modal -->\n"
            + "\n"
            + "\n"
            + "<footer id=\"footer\">\n"
            + "    <div class=\"container\">\n"
            + "        <div class=\"row hidden-xs\">\n"
            + "            <dl class=\"col-sm-2 site-link\">\n"
            + "                <dt>网站相关</dt>\n"
            + "                <dd><a href=\"/about\">关于我们</a></dd>\n"
            + "                <dd><a href=\"/tos\">服务条款</a></dd>\n"
            + "                <dd><a href=\"/faq\">帮助中心</a></dd>\n"
            + "                <dd><a href=\"/repu\">声望与权限</a></dd>\n"
            + "                <dd><a href=\"/markdown\">编辑器语法</a></dd>\n"
            + "                <dd><a href=\"//weekly.segmentfault.com/\">每周精选</a></dd>\n"
            + "                <dd><a href=\"/app\">App 下载</a></dd>\n"
            + "                <dd><a href=\"/community\">社区服务中心</a></dd>\n"
            + "            </dl>\n"
            + "            <dl class=\"col-sm-2 site-link\">\n"
            + "                <dt>联系合作</dt>\n"
            + "                <dd><a href=\"/contact\">联系我们</a></dd>\n"
            + "                <dd><a href=\"/hiring\">加入我们</a></dd>\n"
            + "                <dd><a href=\"/link\">合作伙伴</a></dd>\n"
            + "                <dd><a href=\"/press\">媒体报道</a></dd>\n"
            + "                <dd><a href=\"https://board.segmentfault.com/\">建议反馈</a></dd>\n"
            + "                            </dl>\n"
            + "            <dl class=\"col-sm-2 site-link\">\n"
            + "                <dt>常用链接</dt>\n"
            + "                                                <dd><a href=\"//chrome.google.com/webstore/detail/segmentfault-%E7%AC%94%E8%AE%B0/pjklfdmleagfaekibdccmhlhellefcfo\" target=\"_blank\">笔记插件: Chrome</a></dd>\n"
            + "                                                                <dd><a href=\"//addons.mozilla.org/zh-CN/firefox/addon/sf-note-ext/\" target=\"_blank\">笔记插件: Firefox</a></dd>\n"
            + "                                                                <dd>订阅：<a href=\"/feeds\">问答</a> / <a href=\"/feeds/blogs\">文章</a></dd>\n"
            + "                                                                <dd><a href=\"//mirrors.segmentfault.com/\" target=\"_blank\">文档镜像</a></dd>\n"
            + "                                                                <dd><a href=\"//segmentfault.com/blog/interview\" target=\"_blank\">社区访谈</a></dd>\n"
            + "                                                                <dd><a href=\"//segmentfault.com/d-day\" target=\"_blank\">D-DAY 技术沙龙</a></dd>\n"
            + "                                                                <dd><a href=\"//segmentfault.com/hackathon\" target=\"_blank\">黑客马拉松 Hackathon</a></dd>\n"
            + "                                                                <dd><a href=\"//namebeta.com/\" target=\"_blank\">域名搜索注册</a></dd>\n"
            + "                                                                <dd><a href=\"https://shop165859711.taobao.com/\" target=\"_blank\">周边店铺</a></dd>\n"
            + "                                            </dl>\n"
            + "            <dl class=\"col-sm-2 site-link\">\n"
            + "                <dt>关注我们</dt>\n"
            + "                                <dd><a href=\"//github.com/SegmentFault\" target=\"_blank\">Github</a></dd>\n"
            + "                                <dd><a href=\"//twitter.com/segment_fault\" target=\"_blank\">Twitter</a></dd>\n"
            + "                                <dd><a href=\"http://weibo.com/segmentfault\" target=\"_blank\">新浪微博</a></dd>\n"
            + "                                <dd><a href=\"//segmentfault.com/blog/segmentfault_team\" target=\"_blank\">团队日志</a></dd>\n"
            + "                                <dd><a href=\"//segmentfault.com/blog/segmentfault\" target=\"_blank\">产品技术日志</a></dd>\n"
            + "                                <dd><a href=\"//segmentfault.com/blog/community_admin\" target=\"_blank\">社区运营日志</a></dd>\n"
            + "                                <dd><a href=\"//segmentfault.com/blog/segmentfault_news\" target=\"_blank\">市场运营日志</a></dd>\n"
            + "                            </dl>\n"
            + "            <dl class=\"col-sm-4 site-link\" id=\"license\">\n"
            + "                <dt>内容许可</dt>\n"
            + "                <dd>除特别说明外，用户内容均采用 <a rel=\"license\" target=\"_blank\" href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/\">知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议</a> 进行许可\n"
            + "                </dd>\n"
            + "                <dd>本站由 <a target=\"_blank\" href=\"https://www.upyun.com/?utm_source=segmentfault&amp;utm_medium=link&amp;utm_campaign=upyun&amp;md=segmentfault\">又拍云</a> 提供 CDN 存储服务\n"
            + "                </dd>\n"
            + "            </dl>\n"
            + "        </div>\n"
            + "        <div class=\"copyright\">\n"
            + "            Copyright © 2011-2017 SegmentFault. 当前呈现版本 17.02.05<br>\n"
            + "            <a href=\"http://www.miibeian.gov.cn/\" rel=\"nofollow\">浙ICP备 15005796号-2</a> &nbsp;\n"
            + "            <a target=\"_blank\" href=\"http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010602002000\" rel=\"nofollow\">浙公网安备 33010602002000号</a>\n"
            + "        </div>\n"
            + "        <p class=\"text-center\">\n"
            + "            <a class=\"js__view--selector hidden-sm hidden-md hidden-lg\" data-action=\"mobile\" href=\"javascript:;\">移动版</a>\n"
            + "            <a class=\"js__view--selector hidden-sm hidden-md hidden-lg\" data-action=\"desktop\" href=\"javascript:;\">桌面版</a>\n"
            + "        </p>\n"
            + "    </div>\n"
            + "</footer>\n"
            + "\n"
            + "<div id=\"fixedTools\" class=\"hidden-xs hidden-sm\">\n"
            + "    <a id=\"backtop\" class=\"border-bottom hidden\" href=\"#\">回顶部</a>\n"
            + "\n"
            + "    <div class=\"qrcodeWraper\">\n"
            + "        <a href=\"/app#qrcode\"><span class=\"glyphicon glyphicon-qrcode\"></span></a>\n"
            + "        <img id=\"qrcode\" class=\"border\" alt=\"sf-wechat\" src=\"https://static.segmentfault.com/v-58db88a6/page/img/app/appQrcode.png\">\n"
            + "\n"
            + "        <p class=\"qrcode-text\">扫扫下载 App</p>\n"
            + "    </div>\n"
            + "</div>\n"
            + "\n"
            + "<div class=\"app-promotion-bar\">\n"
            + "    <a href=\"javascript:;\"><i class=\"fa fa-close close\"></i></a>\n"
            + "    <div class=\"icon\"></div>\n"
            + "    <h5 class=\"title h5\">SegmentFault</h5>\n"
            + "    <p class=\"describe\">一起探索更多未知</p>\n"
            + "    <a class=\"download-btn btn btn-sm btn-primary\" href=\"/app#qrcode\">下载 App</a>\n"
            + "</div>\n"
            + "\n"
            + "<script id=\"loginModal\" type=\"text/template\">\n"
            + "    <div class=\"row bg-white login-modal\">\n"
            + "        <div class=\"col-md-4 col-sm-12 col-md-push-7 login-wrap\">\n"
            + "            <h1 class=\"h4 text-muted login-title\">用户登录</h1>\n"
            + "            <form action=\"/api/user/login\" method=\"POST\" role=\"form\" class=\"mt30\">\n"
            + "                <div class=\"form-group\">\n"
            + "                    <label for=\"username\" class=\"control-label\">手机号 或 Email</label>\n"
            + "                    <input type=\"text\" class=\"form-control\" name=\"username\" required placeholder=\"11 位手机号 或 Email\"\n"
            + "                           autocomplete=\"off\">\n"
            + "                </div>\n"
            + "                <div class=\"form-group\">\n"
            + "                    <label class=\"control-label\">密码</label><span class=\"pull-right\"><a\n"
            + "                                href=\"/user/forgot\">忘记密码</a></span>\n"
            + "                    <input type=\"password\" class=\"form-control\" name=\"password\" required placeholder=\"密码\">\n"
            + "                </div>\n"
            + "                <div class=\"form-group clearfix\">\n"
            + "                    <div class=\"checkbox pull-left\">\n"
            + "                        <label><input name=\"remember\" type=\"checkbox\" value=\"1\" checked> 记住登录状态</label>\n"
            + "                    </div>\n"
            + "                    <button type=\"submit\" class=\"btn btn-primary pull-right pl20 pr20\"\n"
            + "                            onclick='ga(\"send\", \"event\", \"email login button\", \"clicked\", \"login modal\");'>登录\n"
            + "                    </button>\n"
            + "                </div>\n"
            + "            </form>\n"
            + "            <p class=\"h4 text-muted visible-xs-block h4\">快速登录</p>\n"
            + "            <div class=\"widget-login mt30\">\n"
            + "                <p class=\"text-muted mt5 mr10 pull-left hidden-xs\">快速登录</p>\n"
            + "                <a href=\"/user/oauth/google\" class=\"\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"google\"});'><span\n"
            + "                            class=\"icon-sn-google\"></span> <strong class=\"visible-xs-inline\">Google 账号</strong></a>\n"
            + "                <a href=\"/user/oauth/github\" class=\"\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"github\"});\");'><span\n"
            + "                            class=\"icon-sn-github\"></span> <strong class=\"visible-xs-inline\">Github 账号</strong></a>\n"
            + "                <a href=\"/user/oauth/weibo\" class=\"\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"weibo\"});'><span\n"
            + "                            class=\"icon-sn-weibo\"></span> <strong class=\"visible-xs-inline\">新浪微博账号</strong></a>\n"
            + "                <a href=\"/user/oauth/qq\" class=\"\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"qq\"});'><span\n"
            + "                            class=\"icon-sn-qq\"></span> <strong class=\"visible-xs-inline\">QQ 账号</strong></a>\n"
            + "                <a href=\"/user/oauth/weixin\" class=\"\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"qq\"});'><span\n"
            + "                            class=\"icon-sn-weixin\"></span> <strong class=\"visible-xs-inline\">微信账号</strong></a>\n"
            + "                <a href=\"/user/oauth/linkedin\" class=\"\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"linkedin\"});'><span\n"
            + "                            class=\"icon-sn-linkedin\"></span> <strong class=\"visible-xs-inline\">LinkedIn 账号</strong></a>\n"
            + "                <span id=\"loginShowMore\" style=\"cursor: pointer\" class=\"mb5\"><span class=\"icon-sn-dotted\"></span><strong\n"
            + "                            class=\"visible-xs-inline\">•••</strong></span>\n"
            + "                <a href=\"/user/oauth/twitter\" class=\" hidden\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"twitter\"});'><span\n"
            + "                            class=\"icon-sn-twitter\"></span> <strong class=\"visible-xs-inline\">Twitter 账号</strong></a>\n"
            + "                <a href=\"/user/oauth/facebook\" class=\" hidden\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"facebook\"});'><span\n"
            + "                            class=\"icon-sn-facebook\"></span> <strong class=\"visible-xs-inline\">Facebook 账号</strong></a>\n"
            + "                <a href=\"/user/oauth/douban\" class=\" hidden\"\n"
            + "                   onclick='ga(\"send\", \"event\", \"3rd login button\", \"clicked\", \"login modal\", {media: \"douban\"});'><span\n"
            + "                            class=\"icon-sn-douban\"></span> <strong class=\"visible-xs-inline\">豆瓣账号</strong></a>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "        <div class=\"login-vline hidden-xs hidden-sm\"></div>\n"
            + "        <div class=\"col-md-4 col-md-pull-3 col-sm-12 login-wrap\">\n"
            + "            <h1 class=\"h4 text-muted login-title\">注册新账号</h1>\n"
            + "            <form action=\"/api/user/phone/register\" method=\"POST\" role=\"form\" class=\"mt30\">\n"
            + "                <div class=\"form-group\">\n"
            + "                    <label for=\"name\" class=\"control-label\">名字</label>\n"
            + "                    <input type=\"text\" class=\"form-control\" name=\"name\" required placeholder=\"真实姓名或常用昵称\">\n"
            + "                </div>\n"
            + "\n"
            + "\n"
            + "                <div class=\"form-group js-register-switch-box\">\n"
            + "                    <div class=\"mb10\">\n"
            + "                        <label class=\"radio-inline\">\n"
            + "                            <input type=\"radio\" name=\"register_type\" value=\"phone\" checked> 用手机号注册\n"
            + "                        </label>\n"
            + "                        <label class=\"radio-inline\">\n"
            + "                            <input type=\"radio\" name=\"register_type\" value=\"mail\"> 用 Email 注册\n"
            + "                        </label>\n"
            + "                    </div>\n"
            + "                    <div class=\"js-register-switch-content\">\n"
            + "                        <input type=\"phone\" class=\"form-control mb15\" name=\"phone\" required placeholder=\"仅支持大陆手机号\"\n"
            + "                               autocomplete=\"off\">\n"
            + "                        <div class=\"input-group\"><input name=\"code\" type=\"text\"\n"
            + "                                                        class=\"form-control js-user-login__phone-code-value\"\n"
            + "                                                        placeholder=\"短信验证码\">\n"
            + "                            <span class=\"input-group-btn\"><button class=\"btn btn-default js-user-login__phone-vaild-btn\"\n"
            + "                                                                  style=\"width:96px;\" type=\"button\">获取验证码</button></span>\n"
            + "                        </div>\n"
            + "                    </div>\n"
            + "                </div>\n"
            + "\n"
            + "\n"
            + "                <div class=\"form-group\">\n"
            + "                    <label for=\"password\" class=\"control-label\">密码</label>\n"
            + "                    <input type=\"password\" class=\"form-control\" name=\"password\" required placeholder=\"不少于 6 位\">\n"
            + "                </div>\n"
            + "                <div class=\"form-group\" style=\"display:none;\">\n"
            + "                    <label class=\"required control-label\">验证码</label>\n"
            + "                    <input type=\"text\" class=\"form-control\" id=\"captcha\" name=\"captcha\" placeholder=\"请输入下方的验证码\">\n"
            + "                    <div class=\"mt10\"><a id=\"loginReloadCaptcha\" href=\"javascript:void(0)\"><img\n"
            + "                                    data-src=\"/user/captcha?w=240&h=50\" class=\"captcha\" width=\"240\" height=\"50\"/></a>\n"
            + "                    </div>\n"
            + "                </div>\n"
            + "                <div class=\"form-group clearfix\">\n"
            + "                    <div class=\"checkbox pull-left\">\n"
            + "                        同意并接受<a href=\"/tos\" target=\"_blank\">《服务条款》</a>\n"
            + "                    </div>\n"
            + "                    <button type=\"submit\" class=\"btn btn-primary pl20 pr20 pull-right\"\n"
            + "                            onclick='ga(\"send\", \"event\", \"email register button\", \"clicked\", \"login modal\");'>注册\n"
            + "                    </button>\n"
            + "                </div>\n"
            + "            </form>\n"
            + "        </div>\n"
            + "    </div>\n"
            + "    <div class=\"text-center text-muted mt30\">\n"
            + "    </div>\n"
            + "</script>\n"
            + "\n"
            + "\n"
            + "\n"
            + "<script>\n"
            + "    (function (w) {\n"
            + "        w.SF = {\n"
            + "            staticUrl: \"https://static.segmentfault.com/v-58db88a6\"\n"
            + "        };\n"
            + "        w.SF.token = (function () {\n"
            + "    var _S9m70 = //'qZ'\n"
            + "'5'+''///*'p'*/'p'\n"
            + "+/* 'E'//'E' */''+'dd'//'jn'\n"
            + "+'c7'//'b'\n"
            + "+'a64'//'Qu'\n"
            + "+'75'//'N'\n"
            + "+'a'//'OC'\n"
            + "+'b2b'//'hc'\n"
            + "+//'Lqq'\n"
            + "'cc'+//'vS'\n"
            + "'8'+//'5E'\n"
            + "'91d'+//'c'\n"
            + "'6'+''///*'w2'*/'w2'\n"
            + "+//'7'\n"
            + "'e09'+//'Ro'\n"
            + "'3b'+'b67'//'vGv'\n"
            + "+//'L'\n"
            + "'L'+//'Y'\n"
            + "'2a'+''///*'8'*/'8'\n"
            + "+'6'//'Qg'\n"
            + ", _6lR = [[29,30]];\n"
            + "\n"
            + "    for (var i = 0; i < _6lR.length; i ++) {\n"
            + "        _S9m70 = _S9m70.substring(0, _6lR[i][0]) + _S9m70.substring(_6lR[i][1]);\n"
            + "    }\n"
            + "\n"
            + "    return _S9m70;\n"
            + "})();;\n"
            + "    })(window);\n"
            + "\n"
            + "                var lock = {\n"
            + "        type: \"\",\n"
            + "        text: '',\n"
            + "        table: {\"ban_post\":[1,\"\\u4f60\\u5df2\\u7ecf\\u88ab\\u7981\\u8a00, \\u65e0\\u6cd5\\u8fdb\\u884c\\u6b64\\u64cd\\u4f5c, \\u5982\\u6709\\u7591\\u4e49\\u8bf7\\u63d0\\u4ea4\\u7533\\u8bc9, \\u6216\\u8005\\u53d1\\u90ae\\u4ef6\\u5230pr@segmentfault.com\"]}\n"
            + "    };\n"
            + "</script>\n"
            + "\n"
            + "    <script crossorigin=\"\" src=\"https://static.segmentfault.com/v-58db88a6/3rd/assets.js\"></script>\n"
            + "    <script crossorigin=\"\" src=\"https://static.segmentfault.com/v-58db88a6/blog/script/post.min.js\"></script>\n"
            + "\n"
            + "<script async=\"\" src=\"//sponsor.segmentfault.com/asyncjs.php\"></script>\n"
            + "\n"
            + "<script>\n"
            + "    var _gaq = _gaq || [];\n"
            + "    _gaq.push(['_setAccount', 'UA-918487-8']);\n"
            + "    _gaq.push(['_trackPageview']);\n"
            + "    (function (i, s, o, g, r, a, m) {\n"
            + "        i['GoogleAnalyticsObject'] = r;\n"
            + "        i[r] = i[r] || function () {\n"
            + "                    (i[r].q = i[r].q || []).push(arguments)\n"
            + "                }, i[r].l = 1 * new Date();\n"
            + "        a = s.createElement(o),\n"
            + "                m = s.getElementsByTagName(o)[0];\n"
            + "        a.async = 1;\n"
            + "        a.src = g;\n"
            + "        m.parentNode.insertBefore(a, m)\n"
            + "    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');\n"
            + "\n"
            + "            \n"
            + "        \n"
            + "\n"
            + "            \n"
            + "\n"
            + "    ga('create', 'UA-918487-8', 'auto', {\n"
            + "        'userID'\n"
            + "    : 0,\n"
            + "        'createdTime'\n"
            + "    : 0,\n"
            + "        'now'\n"
            + "    : 1490788468 });\n"
            + "    ga('set', 'dimension1', 'guest');\n"
            + "    ga('send', 'pageview');\n"
            + "\n"
            + "</script>\n"
            + "\n"
            + "<script>\n"
            + "    var _hmt = _hmt || [];\n"
            + "    (function () {\n"
            + "        var hm = document.createElement(\"script\");\n"
            + "        hm.src = \"//hm.baidu.com/hm.js?e23800c454aa573c0ccb16b52665ac26\";\n"
            + "        var s = document.getElementsByTagName(\"script\")[0];\n"
            + "        s.parentNode.insertBefore(hm, s);\n"
            + "    })();\n"
            + "</script>\n"
            + "\n"
            + "\n"
            + "\n"
            + "\n"
            + "<iframe id=\"p_analyse_iframe\" src=\"https://cookie.pingxx.com/?puid=TDejjbZrGZaUNl8CDjcOw89KEDNJfGSs\" style=\"display: none;\"></iframe><div id=\"noteWidget\" class=\"noteWidget hidden hidden-xs\">\n"
            + "    <div class=\"noteWidget-header clearfix\">\n"
            + "        <h2 class=\"h4 pull-left\">记笔记</h2>\n"
            + "        <ul class=\"list-inline pull-right mb0\">\n"
            + "            <li id=\"noteWidgetMinimize\"><span class=\"icon-minimize\"></span></li><li id=\"noteWidgetZoom\"><span class=\"icon-zoom\"></span></li><li id=\"noteWidgetClose\"><span class=\"icon-close\"></span></li>\n"
            + "        </ul>\n"
            + "    </div>\n"
            + "    <form method=\"POST\" action=\"/api/notes/add\" role=\"form\">\n"
            + "        <div class=\"form-group\">\n"
            + "            <label for=\"title\" class=\"sr-only\">标题</label>\n"
            + "            <input type=\"hidden\" value=\"\" id=\"draftId\">\n"
            + "            <input type=\"text\" name=\"title\" data-error=\"\" autocomplete=\"off\" class=\"form-control\" placeholder=\"笔记描述\" value=\"\">\n"
            + "        </div>\n"
            + "        <div class=\"editor-config clearfix\">\n"
            + "            <select name=\"lang\" class=\"form-control pull-left input-sm\">\n"
            + "                <optgroup label=\"文本语法\">\n"
            + "                    <option value=\"text\" data-mode=\"text\">纯文本</option>\n"
            + "                    <option value=\"markdown\" data-mode=\"markdown\">Markdown</option>\n"
            + "                    <option value=\"javascript\" data-mode=\"javascript\">Javascript</option>\n"
            + "                    <option value=\"css\" data-mode=\"css\">CSS</option>\n"
            + "                    <option value=\"html5\" data-mode=\"htmlmixed\">HTML</option>\n"
            + "                    <option value=\"php\" data-mode=\"php\">PHP</option>\n"
            + "                    <option value=\"python\" data-mode=\"python\">Python</option>\n"
            + "                    <option value=\"ruby\" data-mode=\"ruby\">Ruby</option>\n"
            + "                    <option value=\"go\" data-mode=\"go\">Go</option>\n"
            + "                    <option value=\"c\" data-mode=\"clike\">C/C++</option>\n"
            + "                    <option value=\"java\" data-mode=\"java\">Java</option>\n"
            + "                    <option value=\"bash\" data-mode=\"shell\">Shell/Bash</option>\n"
            + "                </optgroup>\n"
            + "            </select>\n"
            + "            <div class=\"pull-right hidden-xs\">\n"
            + "                <select name=\"indentWithTabs\" class=\"form-control inline-block input-sm\">\n"
            + "                    <optgroup label=\"缩进模式\">\n"
            + "                        <option value=\"false\">空格缩进</option>\n"
            + "                        <option value=\"true\">Tabs 缩进</option>\n"
            + "                    </optgroup>\n"
            + "                </select>\n"
            + "                <select name=\"tabSize\" class=\"form-control inline-block input-sm\">\n"
            + "                    <optgroup label=\"缩进大小\">\n"
            + "                        <option value=\"2\">2</option>\n"
            + "                        <option value=\"4\" selected=\"\">4</option>\n"
            + "                    </optgroup>\n"
            + "                </select>\n"
            + "                <select name=\"lineWrap\" class=\"form-control inline-block input-sm\">\n"
            + "                    <optgroup label=\"换行方式\">\n"
            + "                        <option value=\"true\">自动换行</option>\n"
            + "                        <option value=\"false\">不换行</option>\n"
            + "                    </optgroup>\n"
            + "                </select>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "        <textarea id=\"codeMirror\" class=\"form-control\" style=\"display: none;\"></textarea><div class=\"CodeMirror cm-s-default CodeMirror-wrap\"><div style=\"overflow: hidden; position: relative; width: 3px; height: 0px;\"><textarea autocorrect=\"off\" autocapitalize=\"off\" spellcheck=\"false\" style=\"position: absolute; padding: 0px; width: 1000px; height: 1em; outline: none;\" tabindex=\"0\"></textarea></div><div class=\"CodeMirror-hscrollbar\" style=\"left: 0px;\"><div style=\"height: 100%; min-height: 1px;\"></div></div><div class=\"CodeMirror-vscrollbar\"><div style=\"min-width: 1px;\"></div></div><div class=\"CodeMirror-scrollbar-filler\"></div><div class=\"CodeMirror-gutter-filler\"></div><div class=\"CodeMirror-scroll\" tabindex=\"-1\"><div class=\"CodeMirror-sizer\" style=\"margin-left: 0px;\"><div style=\"position: relative;\"><div class=\"CodeMirror-lines\"><div style=\"position: relative; outline: none;\"><div class=\"CodeMirror-measure\"><pre><span>xxxxxxxxxx</span></pre></div><div class=\"CodeMirror-measure\"></div><div style=\"position: relative; z-index: 1;\"></div><div class=\"CodeMirror-cursors\"></div><div class=\"CodeMirror-code\"></div></div></div></div></div><div style=\"position: absolute; height: 30px; width: 1px;\"></div><div class=\"CodeMirror-gutters\"><div class=\"CodeMirror-gutter CodeMirror-linenumbers\" style=\"width: 1px;\"></div></div></div></div>\n"
            + "        <div class=\"mt20 clearfix\">\n"
            + "            <div class=\"pull-right\">\n"
            + "                <span class=\"text-muted hidden\" id=\"editorStatus\">已保存</span>\n"
            + "                <a id=\"dropIt\" href=\"javascript:void(0);\" class=\"mr10 hidden\">[舍弃]</a>\n"
            + "                <button data-type=\"note\" id=\"publishIt2\" class=\"btn btn-default ml10\" data-id=\"\" data-do=\"add\" data-url=\"\" data-text=\"保存私密笔记\" data-name=\"\">保存私密笔记</button>\n"
            + "                <button data-type=\"note\" id=\"publishIt\" class=\"btn btn-primary ml10\" data-id=\"\" data-do=\"add\" data-url=\"\" data-text=\"保存公开笔记\" data-name=\"\">保存公开笔记</button>\n"
            + "                </div>\n"
            + "            </div>\n"
            + "        </form></div>\n"
            + "    \n"
            + "<div id=\"atwho-container\"><div id=\"atwho-ground-d322c9dc1490788471839\"><div class=\"atwho-view\" id=\"at-view-64\"><ul class=\"atwho-view-ul\"></ul></div></div></div></body></html>";

    String text="src=\"https://cookie.pingxx.com/?puid=TDejjbZrGZaUNl8CDjcOw89KEDNJfGSs\"";
    String pattern = "(?<=src=\")[^\"]*(?=\")";

//    String pattern = "(?<=abc).*";

    // 创建 Pattern 对象
    Pattern r = Pattern.compile(pattern);

    // 现在创建 matcher 对象
    Matcher m = r.matcher(html);
    while (m.find()) {
      System.out.println("Found value: " + m.group(0));
    }

  }
}
